version: "3.9"

services:
  php:
    build: ./php
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: eatables
      MYSQL_USER: eatuser
      MYSQL_PASSWORD: eatpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data: